<?php
// Internationale Provider-Datenbank
return [
    /***** DEUTSCHLAND *****/
    // Deutsche Telekom
    '178.' => ['name' => 'Deutsche Telekom AG', 'asn' => 'AS3320', 'country' => 'DE', 'type' => 'ISP'],
    '91.' => ['name' => 'Deutsche Telekom AG', 'asn' => 'AS3320', 'country' => 'DE', 'type' => 'ISP'],
    '217.' => ['name' => 'Deutsche Telekom AG', 'asn' => 'AS3320', 'country' => 'DE', 'type' => 'ISP'],
    
    // Vodafone DE
    '77.20.' => ['name' => 'Vodafone GmbH', 'asn' => 'AS3209', 'country' => 'DE', 'type' => 'ISP'],
    '31.16.' => ['name' => 'Vodafone GmbH', 'asn' => 'AS3209', 'country' => 'DE', 'type' => 'ISP'],
    
    // Telefónica (O2)
    '79.224.' => ['name' => 'Telefónica Germany', 'asn' => 'AS6805', 'country' => 'DE', 'type' => 'ISP'],
    '84.128.' => ['name' => 'Telefónica Germany', 'asn' => 'AS6805', 'country' => 'DE', 'type' => 'ISP'],
    
    /***** FRANKREICH *****/
    // Orange France
    '78.192.' => ['name' => 'Orange S.A.', 'asn' => 'AS3215', 'country' => 'FR', 'type' => 'ISP', 'website' => 'https://www.orange.fr'],
    '78.193.' => ['name' => 'Orange S.A.', 'asn' => 'AS3215', 'country' => 'FR', 'type' => 'ISP'],
    '78.194.' => ['name' => 'Orange S.A.', 'asn' => 'AS3215', 'country' => 'FR', 'type' => 'ISP'],
    '78.195.' => ['name' => 'Orange S.A.', 'asn' => 'AS3215', 'country' => 'FR', 'type' => 'ISP'],
    '78.196.' => ['name' => 'Orange S.A.', 'asn' => 'AS3215', 'country' => 'FR', 'type' => 'ISP'],
    '78.197.' => ['name' => 'Orange S.A.', 'asn' => 'AS3215', 'country' => 'FR', 'type' => 'ISP'],
    '78.198.' => ['name' => 'Orange S.A.', 'asn' => 'AS3215', 'country' => 'FR', 'type' => 'ISP'],
    '78.199.' => ['name' => 'Orange S.A.', 'asn' => 'AS3215', 'country' => 'FR', 'type' => 'ISP'],
    '81.253.' => ['name' => 'Orange S.A.', 'asn' => 'AS3215', 'country' => 'FR', 'type' => 'ISP'],
    '81.254.' => ['name' => 'Orange S.A.', 'asn' => 'AS3215', 'country' => 'FR', 'type' => 'ISP'],
    '81.255.' => ['name' => 'Orange S.A.', 'asn' => 'AS3215', 'country' => 'FR', 'type' => 'ISP'],
    '82.127.' => ['name' => 'Orange S.A.', 'asn' => 'AS3215', 'country' => 'FR', 'type' => 'ISP'],
    '82.224.' => ['name' => 'Orange S.A.', 'asn' => 'AS3215', 'country' => 'FR', 'type' => 'ISP'],
    '83.112.' => ['name' => 'Orange S.A.', 'asn' => 'AS3215', 'country' => 'FR', 'type' => 'ISP'],
    '83.113.' => ['name' => 'Orange S.A.', 'asn' => 'AS3215', 'country' => 'FR', 'type' => 'ISP'],
    '83.114.' => ['name' => 'Orange S.A.', 'asn' => 'AS3215', 'country' => 'FR', 'type' => 'ISP'],
    '83.115.' => ['name' => 'Orange S.A.', 'asn' => 'AS3215', 'country' => 'FR', 'type' => 'ISP'],
    '83.116.' => ['name' => 'Orange S.A.', 'asn' => 'AS3215', 'country' => 'FR', 'type' => 'ISP'],
    '83.117.' => ['name' => 'Orange S.A.', 'asn' => 'AS3215', 'country' => 'FR', 'type' => 'ISP'],
    '83.118.' => ['name' => 'Orange S.A.', 'asn' => 'AS3215', 'country' => 'FR', 'type' => 'ISP'],
    '83.119.' => ['name' => 'Orange S.A.', 'asn' => 'AS3215', 'country' => 'FR', 'type' => 'ISP'],
    '83.120.' => ['name' => 'Orange S.A.', 'asn' => 'AS3215', 'country' => 'FR', 'type' => 'ISP'],
    '83.121.' => ['name' => 'Orange S.A.', 'asn' => 'AS3215', 'country' => 'FR', 'type' => 'ISP'],
    '83.122.' => ['name' => 'Orange S.A.', 'asn' => 'AS3215', 'country' => 'FR', 'type' => 'ISP'],
    '83.123.' => ['name' => 'Orange S.A.', 'asn' => 'AS3215', 'country' => 'FR', 'type' => 'ISP'],
    '83.124.' => ['name' => 'Orange S.A.', 'asn' => 'AS3215', 'country' => 'FR', 'type' => 'ISP'],
    '83.125.' => ['name' => 'Orange S.A.', 'asn' => 'AS3215', 'country' => 'FR', 'type' => 'ISP'],
    '83.126.' => ['name' => 'Orange S.A.', 'asn' => 'AS3215', 'country' => 'FR', 'type' => 'ISP'],
    '83.127.' => ['name' => 'Orange S.A.', 'asn' => 'AS3215', 'country' => 'FR', 'type' => 'ISP'],
    '86.192.' => ['name' => 'Orange S.A.', 'asn' => 'AS3215', 'country' => 'FR', 'type' => 'ISP'],
    '86.193.' => ['name' => 'Orange S.A.', 'asn' => 'AS3215', 'country' => 'FR', 'type' => 'ISP'],
    '86.194.' => ['name' => 'Orange S.A.', 'asn' => 'AS3215', 'country' => 'FR', 'type' => 'ISP'],
    '86.195.' => ['name' => 'Orange S.A.', 'asn' => 'AS3215', 'country' => 'FR', 'type' => 'ISP'],
    '86.196.' => ['name' => 'Orange S.A.', 'asn' => 'AS3215', 'country' => 'FR', 'type' => 'ISP'],
    '86.197.' => ['name' => 'Orange S.A.', 'asn' => 'AS3215', 'country' => 'FR', 'type' => 'ISP'],
    '86.198.' => ['name' => 'Orange S.A.', 'asn' => 'AS3215', 'country' => 'FR', 'type' => 'ISP'],
    '86.199.' => ['name' => 'Orange S.A.', 'asn' => 'AS3215', 'country' => 'FR', 'type' => 'ISP'],
    '90.80.' => ['name' => 'Orange S.A.', 'asn' => 'AS3215', 'country' => 'FR', 'type' => 'ISP'],
    '90.81.' => ['name' => 'Orange S.A.', 'asn' => 'AS3215', 'country' => 'FR', 'type' => 'ISP'],
    '90.82.' => ['name' => 'Orange S.A.', 'asn' => 'AS3215', 'country' => 'FR', 'type' => 'ISP'],
    '90.83.' => ['name' => 'Orange S.A.', 'asn' => 'AS3215', 'country' => 'FR', 'type' => 'ISP'],
    '90.84.' => ['name' => 'Orange S.A.', 'asn' => 'AS3215', 'country' => 'FR', 'type' => 'ISP'],
    '90.85.' => ['name' => 'Orange S.A.', 'asn' => 'AS3215', 'country' => 'FR', 'type' => 'ISP'],
    '90.86.' => ['name' => 'Orange S.A.', 'asn' => 'AS3215', 'country' => 'FR', 'type' => 'ISP'],
    '90.87.' => ['name' => 'Orange S.A.', 'asn' => 'AS3215', 'country' => 'FR', 'type' => 'ISP'],
    '90.88.' => ['name' => 'Orange S.A.', 'asn' => 'AS3215', 'country' => 'FR', 'type' => 'ISP'],
    '90.89.' => ['name' => 'Orange S.A.', 'asn' => 'AS3215', 'country' => 'FR', 'type' => 'ISP'],
    '90.90.' => ['name' => 'Orange S.A.', 'asn' => 'AS3215', 'country' => 'FR', 'type' => 'ISP'],
    '90.91.' => ['name' => 'Orange S.A.', 'asn' => 'AS3215', 'country' => 'FR', 'type' => 'ISP'],
    '90.92.' => ['name' => 'Orange S.A.', 'asn' => 'AS3215', 'country' => 'FR', 'type' => 'ISP'],
    '90.93.' => ['name' => 'Orange S.A.', 'asn' => 'AS3215', 'country' => 'FR', 'type' => 'ISP'],
    '90.94.' => ['name' => 'Orange S.A.', 'asn' => 'AS3215', 'country' => 'FR', 'type' => 'ISP'],
    '90.95.' => ['name' => 'Orange S.A.', 'asn' => 'AS3215', 'country' => 'FR', 'type' => 'ISP'],
    '90.96.' => ['name' => 'Orange S.A.', 'asn' => 'AS3215', 'country' => 'FR', 'type' => 'ISP'],
    '90.97.' => ['name' => 'Orange S.A.', 'asn' => 'AS3215', 'country' => 'FR', 'type' => 'ISP'],
    '90.98.' => ['name' => 'Orange S.A.', 'asn' => 'AS3215', 'country' => 'FR', 'type' => 'ISP'],
    '90.99.' => ['name' => 'Orange S.A.', 'asn' => 'AS3215', 'country' => 'FR', 'type' => 'ISP'],
    '2a01:cb00:' => ['name' => 'Orange S.A.', 'asn' => 'AS3215', 'country' => 'FR', 'type' => 'ISP', 'ipv6' => true],
    
    // Free (Iliad)
    '78.224.' => ['name' => 'Free (Iliad)', 'asn' => 'AS12322', 'country' => 'FR', 'type' => 'ISP', 'website' => 'https://www.free.fr'],
    '78.225.' => ['name' => 'Free (Iliad)', 'asn' => 'AS12322', 'country' => 'FR', 'type' => 'ISP'],
    '78.226.' => ['name' => 'Free (Iliad)', 'asn' => 'AS12322', 'country' => 'FR', 'type' => 'ISP'],
    '78.227.' => ['name' => 'Free (Iliad)', 'asn' => 'AS12322', 'country' => 'FR', 'type' => 'ISP'],
    '78.228.' => ['name' => 'Free (Iliad)', 'asn' => 'AS12322', 'country' => 'FR', 'type' => 'ISP'],
    '78.229.' => ['name' => 'Free (Iliad)', 'asn' => 'AS12322', 'country' => 'FR', 'type' => 'ISP'],
    '78.230.' => ['name' => 'Free (Iliad)', 'asn' => 'AS12322', 'country' => 'FR', 'type' => 'ISP'],
    '78.231.' => ['name' => 'Free (Iliad)', 'asn' => 'AS12322', 'country' => 'FR', 'type' => 'ISP'],
    '78.232.' => ['name' => 'Free (Iliad)', 'asn' => 'AS12322', 'country' => 'FR', 'type' => 'ISP'],
    '78.233.' => ['name' => 'Free (Iliad)', 'asn' => 'AS12322', 'country' => 'FR', 'type' => 'ISP'],
    '78.234.' => ['name' => 'Free (Iliad)', 'asn' => 'AS12322', 'country' => 'FR', 'type' => 'ISP'],
    '78.235.' => ['name' => 'Free (Iliad)', 'asn' => 'AS12322', 'country' => 'FR', 'type' => 'ISP'],
    '78.236.' => ['name' => 'Free (Iliad)', 'asn' => 'AS12322', 'country' => 'FR', 'type' => 'ISP'],
    '78.237.' => ['name' => 'Free (Iliad)', 'asn' => 'AS12322', 'country' => 'FR', 'type' => 'ISP'],
    '78.238.' => ['name' => 'Free (Iliad)', 'asn' => 'AS12322', 'country' => 'FR', 'type' => 'ISP'],
    '78.239.' => ['name' => 'Free (Iliad)', 'asn' => 'AS12322', 'country' => 'FR', 'type' => 'ISP'],
    '78.240.' => ['name' => 'Free (Iliad)', 'asn' => 'AS12322', 'country' => 'FR', 'type' => 'ISP'],
    '78.241.' => ['name' => 'Free (Iliad)', 'asn' => 'AS12322', 'country' => 'FR', 'type' => 'ISP'],
    '78.242.' => ['name' => 'Free (Iliad)', 'asn' => 'AS12322', 'country' => 'FR', 'type' => 'ISP'],
    '78.243.' => ['name' => 'Free (Iliad)', 'asn' => 'AS12322', 'country' => 'FR', 'type' => 'ISP'],
    '78.244.' => ['name' => 'Free (Iliad)', 'asn' => 'AS12322', 'country' => 'FR', 'type' => 'ISP'],
    '78.245.' => ['name' => 'Free (Iliad)', 'asn' => 'AS12322', 'country' => 'FR', 'type' => 'ISP'],
    '78.246.' => ['name' => 'Free (Iliad)', 'asn' => 'AS12322', 'country' => 'FR', 'type' => 'ISP'],
    '78.247.' => ['name' => 'Free (Iliad)', 'asn' => 'AS12322', 'country' => 'FR', 'type' => 'ISP'],
    '78.248.' => ['name' => 'Free (Iliad)', 'asn' => 'AS12322', 'country' => 'FR', 'type' => 'ISP'],
    '78.249.' => ['name' => 'Free (Iliad)', 'asn' => 'AS12322', 'country' => 'FR', 'type' => 'ISP'],
    '78.250.' => ['name' => 'Free (Iliad)', 'asn' => 'AS12322', 'country' => 'FR', 'type' => 'ISP'],
    '78.251.' => ['name' => 'Free (Iliad)', 'asn' => 'AS12322', 'country' => 'FR', 'type' => 'ISP'],
    '78.252.' => ['name' => 'Free (Iliad)', 'asn' => 'AS12322', 'country' => 'FR', 'type' => 'ISP'],
    '78.253.' => ['name' => 'Free (Iliad)', 'asn' => 'AS12322', 'country' => 'FR', 'type' => 'ISP'],
    '78.254.' => ['name' => 'Free (Iliad)', 'asn' => 'AS12322', 'country' => 'FR', 'type' => 'ISP'],
    '78.255.' => ['name' => 'Free (Iliad)', 'asn' => 'AS12322', 'country' => 'FR', 'type' => 'ISP'],
    '88.160.' => ['name' => 'Free (Iliad)', 'asn' => 'AS12322', 'country' => 'FR', 'type' => 'ISP'],
    '88.161.' => ['name' => 'Free (Iliad)', 'asn' => 'AS12322', 'country' => 'FR', 'type' => 'ISP'],
    '88.162.' => ['name' => 'Free (Iliad)', 'asn' => 'AS12322', 'country' => 'FR', 'type' => 'ISP'],
    '88.163.' => ['name' => 'Free (Iliad)', 'asn' => 'AS12322', 'country' => 'FR', 'type' => 'ISP'],
    '88.164.' => ['name' => 'Free (Iliad)', 'asn' => 'AS12322', 'country' => 'FR', 'type' => 'ISP'],
    '88.165.' => ['name' => 'Free (Iliad)', 'asn' => 'AS12322', 'country' => 'FR', 'type' => 'ISP'],
    '88.166.' => ['name' => 'Free (Iliad)', 'asn' => 'AS12322', 'country' => 'FR', 'type' => 'ISP'],
    '88.167.' => ['name' => 'Free (Iliad)', 'asn' => 'AS12322', 'country' => 'FR', 'type' => 'ISP'],
    '88.168.' => ['name' => 'Free (Iliad)', 'asn' => 'AS12322', 'country' => 'FR', 'type' => 'ISP'],
    '88.169.' => ['name' => 'Free (Iliad)', 'asn' => 'AS12322', 'country' => 'FR', 'type' => 'ISP'],
    '88.170.' => ['name' => 'Free (Iliad)', 'asn' => 'AS12322', 'country' => 'FR', 'type' => 'ISP'],
    '88.171.' => ['name' => 'Free (Iliad)', 'asn' => 'AS12322', 'country' => 'FR', 'type' => 'ISP'],
    '88.172.' => ['name' => 'Free (Iliad)', 'asn' => 'AS12322', 'country' => 'FR', 'type' => 'ISP'],
    '88.173.' => ['name' => 'Free (Iliad)', 'asn' => 'AS12322', 'country' => 'FR', 'type' => 'ISP'],
    '88.174.' => ['name' => 'Free (Iliad)', 'asn' => 'AS12322', 'country' => 'FR', 'type' => 'ISP'],
    '88.175.' => ['name' => 'Free (Iliad)', 'asn' => 'AS12322', 'country' => 'FR', 'type' => 'ISP'],
    '2a01:e0c:' => ['name' => 'Free (Iliad)', 'asn' => 'AS12322', 'country' => 'FR', 'type' => 'ISP', 'ipv6' => true],
    
    // SFR
    '81.49.' => ['name' => 'SFR', 'asn' => 'AS15557', 'country' => 'FR', 'type' => 'ISP', 'website' => 'https://www.sfr.fr'],
    '81.50.' => ['name' => 'SFR', 'asn' => 'AS15557', 'country' => 'FR', 'type' => 'ISP'],
    '81.51.' => ['name' => 'SFR', 'asn' => 'AS15557', 'country' => 'FR', 'type' => 'ISP'],
    '81.52.' => ['name' => 'SFR', 'asn' => 'AS15557', 'country' => 'FR', 'type' => 'ISP'],
    '81.53.' => ['name' => 'SFR', 'asn' => 'AS15557', 'country' => 'FR', 'type' => 'ISP'],
    '81.54.' => ['name' => 'SFR', 'asn' => 'AS15557', 'country' => 'FR', 'type' => 'ISP'],
    '81.55.' => ['name' => 'SFR', 'asn' => 'AS15557', 'country' => 'FR', 'type' => 'ISP'],
    '81.56.' => ['name' => 'SFR', 'asn' => 'AS15557', 'country' => 'FR', 'type' => 'ISP'],
    '81.57.' => ['name' => 'SFR', 'asn' => 'AS15557', 'country' => 'FR', 'type' => 'ISP'],
    '81.58.' => ['name' => 'SFR', 'asn' => 'AS15557', 'country' => 'FR', 'type' => 'ISP'],
    '81.59.' => ['name' => 'SFR', 'asn' => 'AS15557', 'country' => 'FR', 'type' => 'ISP'],
    '81.60.' => ['name' => 'SFR', 'asn' => 'AS15557', 'country' => 'FR', 'type' => 'ISP'],
    '81.61.' => ['name' => 'SFR', 'asn' => 'AS15557', 'country' => 'FR', 'type' => 'ISP'],
    '81.62.' => ['name' => 'SFR', 'asn' => 'AS15557', 'country' => 'FR', 'type' => 'ISP'],
    '81.63.' => ['name' => 'SFR', 'asn' => 'AS15557', 'country' => 'FR', 'type' => 'ISP'],
    '81.64.' => ['name' => 'SFR', 'asn' => 'AS15557', 'country' => 'FR', 'type' => 'ISP'],
    '81.65.' => ['name' => 'SFR', 'asn' => 'AS15557', 'country' => 'FR', 'type' => 'ISP'],
    '81.66.' => ['name' => 'SFR', 'asn' => 'AS15557', 'country' => 'FR', 'type' => 'ISP'],
    '81.67.' => ['name' => 'SFR', 'asn' => 'AS15557', 'country' => 'FR', 'type' => 'ISP'],
    '81.68.' => ['name' => 'SFR', 'asn' => 'AS15557', 'country' => 'FR', 'type' => 'ISP'],
    '81.69.' => ['name' => 'SFR', 'asn' => 'AS15557', 'country' => 'FR', 'type' => 'ISP'],
    '81.70.' => ['name' => 'SFR', 'asn' => 'AS15557', 'country' => 'FR', 'type' => 'ISP'],
    '81.71.' => ['name' => 'SFR', 'asn' => 'AS15557', 'country' => 'FR', 'type' => 'ISP'],
    '81.72.' => ['name' => 'SFR', 'asn' => 'AS15557', 'country' => 'FR', 'type' => 'ISP'],
    '81.73.' => ['name' => 'SFR', 'asn' => 'AS15557', 'country' => 'FR', 'type' => 'ISP'],
    '81.74.' => ['name' => 'SFR', 'asn' => 'AS15557', 'country' => 'FR', 'type' => 'ISP'],
    '81.75.' => ['name' => 'SFR', 'asn' => 'AS15557', 'country' => 'FR', 'type' => 'ISP'],
    '81.76.' => ['name' => 'SFR', 'asn' => 'AS15557', 'country' => 'FR', 'type' => 'ISP'],
    '81.77.' => ['name' => 'SFR', 'asn' => 'AS15557', 'country' => 'FR', 'type' => 'ISP'],
    '81.78.' => ['name' => 'SFR', 'asn' => 'AS15557', 'country' => 'FR', 'type' => 'ISP'],
    '81.79.' => ['name' => 'SFR', 'asn' => 'AS15557', 'country' => 'FR', 'type' => 'ISP'],
    '81.80.' => ['name' => 'SFR', 'asn' => 'AS15557', 'country' => 'FR', 'type' => 'ISP'],
    '81.81.' => ['name' => 'SFR', 'asn' => 'AS15557', 'country' => 'FR', 'type' => 'ISP'],
    '81.82.' => ['name' => 'SFR', 'asn' => 'AS15557', 'country' => 'FR', 'type' => 'ISP'],
    '81.83.' => ['name' => 'SFR', 'asn' => 'AS15557', 'country' => 'FR', 'type' => 'ISP'],
    '81.84.' => ['name' => 'SFR', 'asn' => 'AS15557', 'country' => 'FR', 'type' => 'ISP'],
    '81.85.' => ['name' => 'SFR', 'asn' => 'AS15557', 'country' => 'FR', 'type' => 'ISP'],
    '81.86.' => ['name' => 'SFR', 'asn' => 'AS15557', 'country' => 'FR', 'type' => 'ISP'],
    '81.87.' => ['name' => 'SFR', 'asn' => 'AS15557', 'country' => 'FR', 'type' => 'ISP'],
    '81.88.' => ['name' => 'SFR', 'asn' => 'AS15557', 'country' => 'FR', 'type' => 'ISP'],
    '81.89.' => ['name' => 'SFR', 'asn' => 'AS15557', 'country' => 'FR', 'type' => 'ISP'],
    '81.90.' => ['name' => 'SFR', 'asn' => 'AS15557', 'country' => 'FR', 'type' => 'ISP'],
    '81.91.' => ['name' => 'SFR', 'asn' => 'AS15557', 'country' => 'FR', 'type' => 'ISP'],
    '81.92.' => ['name' => 'SFR', 'asn' => 'AS15557', 'country' => 'FR', 'type' => 'ISP'],
    '81.93.' => ['name' => 'SFR', 'asn' => 'AS15557', 'country' => 'FR', 'type' => 'ISP'],
    '81.94.' => ['name' => 'SFR', 'asn' => 'AS15557', 'country' => 'FR', 'type' => 'ISP'],
    '81.95.' => ['name' => 'SFR', 'asn' => 'AS15557', 'country' => 'FR', 'type' => 'ISP'],
    '81.96.' => ['name' => 'SFR', 'asn' => 'AS15557', 'country' => 'FR', 'type' => 'ISP'],
    '81.97.' => ['name' => 'SFR', 'asn' => 'AS15557', 'country' => 'FR', 'type' => 'ISP'],
    '81.98.' => ['name' => 'SFR', 'asn' => 'AS15557', 'country' => 'FR', 'type' => 'ISP'],
    '81.99.' => ['name' => 'SFR', 'asn' => 'AS15557', 'country' => 'FR', 'type' => 'ISP'],
    '81.100.' => ['name' => 'SFR', 'asn' => 'AS15557', 'country' => 'FR', 'type' => 'ISP'],
    '81.101.' => ['name' => 'SFR', 'asn' => 'AS15557', 'country' => 'FR', 'type' => 'ISP'],
    '81.102.' => ['name' => 'SFR', 'asn' => 'AS15557', 'country' => 'FR', 'type' => 'ISP'],
    '81.103.' => ['name' => 'SFR', 'asn' => 'AS15557', 'country' => 'FR', 'type' => 'ISP'],
    '81.104.' => ['name' => 'SFR', 'asn' => 'AS15557', 'country' => 'FR', 'type' => 'ISP'],
    '81.105.' => ['name' => 'SFR', 'asn' => 'AS15557', 'country' => 'FR', 'type' => 'ISP'],
    '81.106.' => ['name' => 'SFR', 'asn' => 'AS15557', 'country' => 'FR', 'type' => 'ISP'],
    '81.107.' => ['name' => 'SFR', 'asn' => 'AS15557', 'country' => 'FR', 'type' => 'ISP'],
    '81.108.' => ['name' => 'SFR', 'asn' => 'AS15557', 'country' => 'FR', 'type' => 'ISP'],
    '81.109.' => ['name' => 'SFR', 'asn' => 'AS15557', 'country' => 'FR', 'type' => 'ISP'],
    '81.110.' => ['name' => 'SFR', 'asn' => 'AS15557', 'country' => 'FR', 'type' => 'ISP'],
    '81.111.' => ['name' => 'SFR', 'asn' => 'AS15557', 'country' => 'FR', 'type' => 'ISP'],
    '81.112.' => ['name' => 'SFR', 'asn' => 'AS15557', 'country' => 'FR', 'type' => 'ISP'],
    '81.113.' => ['name' => 'SFR', 'asn' => 'AS15557', 'country' => 'FR', 'type' => 'ISP'],
    '81.114.' => ['name' => 'SFR', 'asn' => 'AS15557', 'country' => 'FR', 'type' => 'ISP'],
    '81.115.' => ['name' => 'SFR', 'asn' => 'AS15557', 'country' => 'FR', 'type' => 'ISP'],
    '81.116.' => ['name' => 'SFR', 'asn' => 'AS15557', 'country' => 'FR', 'type' => 'ISP'],
    '81.117.' => ['name' => 'SFR', 'asn' => 'AS15557', 'country' => 'FR', 'type' => 'ISP'],
    '81.118.' => ['name' => 'SFR', 'asn' => 'AS15557', 'country' => 'FR', 'type' => 'ISP'],
    '81.119.' => ['name' => 'SFR', 'asn' => 'AS15557', 'country' => 'FR', 'type' => 'ISP'],
    '81.120.' => ['name' => 'SFR', 'asn' => 'AS15557', 'country' => 'FR', 'type' => 'ISP'],
    '81.121.' => ['name' => 'SFR', 'asn' => 'AS15557', 'country' => 'FR', 'type' => 'ISP'],
    '81.122.' => ['name' => 'SFR', 'asn' => 'AS15557', 'country' => 'FR', 'type' => 'ISP'],
    '81.123.' => ['name' => 'SFR', 'asn' => 'AS15557', 'country' => 'FR', 'type' => 'ISP'],
    '81.124.' => ['name' => 'SFR', 'asn' => 'AS15557', 'country' => 'FR', 'type' => 'ISP'],
    '81.125.' => ['name' => 'SFR', 'asn' => 'AS15557', 'country' => 'FR', 'type' => 'ISP'],
    '81.126.' => ['name' => 'SFR', 'asn' => 'AS15557', 'country' => 'FR', 'type' => 'ISP'],
    '81.127.' => ['name' => 'SFR', 'asn' => 'AS15557', 'country' => 'FR', 'type' => 'ISP'],
    '81.128.' => ['name' => 'SFR', 'asn' => 'AS15557', 'country' => 'FR', 'type' => 'ISP'],
    '81.129.' => ['name' => 'SFR', 'asn' => 'AS15557', 'country' => 'FR', 'type' => 'ISP'],
    '81.130.' => ['name' => 'SFR', 'asn' => 'AS15557', 'country' => 'FR', 'type' => 'ISP'],
    '81.131.' => ['name' => 'SFR', 'asn' => 'AS15557', 'country' => 'FR', 'type' => 'ISP'],
    '81.132.' => ['name' => 'SFR', 'asn' => 'AS15557', 'country' => 'FR', 'type' => 'ISP'],
    '81.133.' => ['name' => 'SFR', 'asn' => 'AS15557', 'country' => 'FR', 'type' => 'ISP'],
    '81.134.' => ['name' => 'SFR', 'asn' => 'AS15557', 'country' => 'FR', 'type' => 'ISP'],
    '81.135.' => ['name' => 'SFR', 'asn' => 'AS15557', 'country' => 'FR', 'type' => 'ISP'],
    '81.136.' => ['name' => 'SFR', 'asn' => 'AS15557', 'country' => 'FR', 'type' => 'ISP'],
    '81.137.' => ['name' => 'SFR', 'asn' => 'AS15557', 'country' => 'FR', 'type' => 'ISP'],
    '81.138.' => ['name' => 'SFR', 'asn' => 'AS15557', 'country' => 'FR', 'type' => 'ISP'],
    '81.139.' => ['name' => 'SFR', 'asn' => 'AS15557', 'country' => 'FR', 'type' => 'ISP'],
    '81.140.' => ['name' => 'SFR', 'asn' => 'AS15557', 'country' => 'FR', 'type' => 'ISP'],
    '81.141.' => ['name' => 'SFR', 'asn' => 'AS15557', 'country' => 'FR', 'type' => 'ISP'],
    '81.142.' => ['name' => 'SFR', 'asn' => 'AS15557', 'country' => 'FR', 'type' => 'ISP'],
    '81.143.' => ['name' => 'SFR', 'asn' => 'AS15557', 'country' => 'FR', 'type' => 'ISP'],
    '81.144.' => ['name' => 'SFR', 'asn' => 'AS15557', 'country' => 'FR', 'type' => 'ISP'],
    '81.145.' => ['name' => 'SFR', 'asn' => 'AS15557', 'country' => 'FR', 'type' => 'ISP'],
    '81.146.' => ['name' => 'SFR', 'asn' => 'AS15557', 'country' => 'FR', 'type' => 'ISP'],
    '81.147.' => ['name' => 'SFR', 'asn' => 'AS15557', 'country' => 'FR', 'type' => 'ISP'],
    '81.148.' => ['name' => 'SFR', 'asn' => 'AS15557', 'country' => 'FR', 'type' => 'ISP'],
    '81.149.' => ['name' => 'SFR', 'asn' => 'AS15557', 'country' => 'FR', 'type' => 'ISP'],
    '81.150.' => ['name' => 'SFR', 'asn' => 'AS15557', 'country' => 'FR', 'type' => 'ISP'],
    '81.151.' => ['name' => 'SFR', 'asn' => 'AS15557', 'country' => 'FR', 'type' => 'ISP'],
    '81.152.' => ['name' => 'SFR', 'asn' => 'AS15557', 'country' => 'FR', 'type' => 'ISP'],
    '81.153.' => ['name' => 'SFR', 'asn' => 'AS15557', 'country' => 'FR', 'type' => 'ISP'],
    '81.154.' => ['name' => 'SFR', 'asn' => 'AS15557', 'country' => 'FR', 'type' => 'ISP'],
    '81.155.' => ['name' => 'SFR', 'asn' => 'AS15557', 'country' => 'FR', 'type' => 'ISP'],
    '81.156.' => ['name' => 'SFR', 'asn' => 'AS15557', 'country' => 'FR', 'type' => 'ISP'],
    '81.157.' => ['name' => 'SFR', 'asn' => 'AS15557', 'country' => 'FR', 'type' => 'ISP'],
    '81.158.' => ['name' => 'SFR', 'asn' => 'AS15557', 'country' => 'FR', 'type' => 'ISP'],
    '81.159.' => ['name' => 'SFR', 'asn' => 'AS15557', 'country' => 'FR', 'type' => 'ISP'],
    '2a01:cb08:' => ['name' => 'SFR', 'asn' => 'AS15557', 'country' => 'FR', 'type' => 'ISP', 'ipv6' => true],
    
    // Bouygues Telecom
    '62.35.' => ['name' => 'Bouygues Telecom', 'asn' => 'AS5410', 'country' => 'FR', 'type' => 'ISP', 'website' => 'https://www.bouyguestelecom.fr'],
    '62.36.' => ['name' => 'Bouygues Telecom', 'asn' => 'AS5410', 'country' => 'FR', 'type' => 'ISP'],
    '62.37.' => ['name' => 'Bouygues Telecom', 'asn' => 'AS5410', 'country' => 'FR', 'type' => 'ISP'],
    '62.38.' => ['name' => 'Bouygues Telecom', 'asn' => 'AS5410', 'country' => 'FR', 'type' => 'ISP'],
    '62.39.' => ['name' => 'Bouygues Telecom', 'asn' => 'AS5410', 'country' => 'FR', 'type' => 'ISP'],
    '62.40.' => ['name' => 'Bouygues Telecom', 'asn' => 'AS5410', 'country' => 'FR', 'type' => 'ISP'],
    '62.41.' => ['name' => 'Bouygues Telecom', 'asn' => 'AS5410', 'country' => 'FR', 'type' => 'ISP'],
    '62.42.' => ['name' => 'Bouygues Telecom', 'asn' => 'AS5410', 'country' => 'FR', 'type' => 'ISP'],
    '62.43.' => ['name' => 'Bouygues Telecom', 'asn' => 'AS5410', 'country' => 'FR', 'type' => 'ISP'],
    '62.44.' => ['name' => 'Bouygues Telecom', 'asn' => 'AS5410', 'country' => 'FR', 'type' => 'ISP'],
    '62.45.' => ['name' => 'Bouygues Telecom', 'asn' => 'AS5410', 'country' => 'FR', 'type' => 'ISP'],
    '62.46.' => ['name' => 'Bouygues Telecom', 'asn' => 'AS5410', 'country' => 'FR', 'type' => 'ISP'],
    '62.47.' => ['name' => 'Bouygues Telecom', 'asn' => 'AS5410', 'country' => 'FR', 'type' => 'ISP'],
    '62.48.' => ['name' => 'Bouygues Telecom', 'asn' => 'AS5410', 'country' => 'FR', 'type' => 'ISP'],
    '62.49.' => ['name' => 'Bouygues Telecom', 'asn' => 'AS5410', 'country' => 'FR', 'type' => 'ISP'],
    '62.50.' => ['name' => 'Bouygues Telecom', 'asn' => 'AS5410', 'country' => 'FR', 'type' => 'ISP'],
    '62.51.' => ['name' => 'Bouygues Telecom', 'asn' => 'AS5410', 'country' => 'FR', 'type' => 'ISP'],
    '62.52.' => ['name' => 'Bouygues Telecom', 'asn' => 'AS5410', 'country' => 'FR', 'type' => 'ISP'],
    '62.53.' => ['name' => 'Bouygues Telecom', 'asn' => 'AS5410', 'country' => 'FR', 'type' => 'ISP'],
    '62.54.' => ['name' => 'Bouygues Telecom', 'asn' => 'AS5410', 'country' => 'FR', 'type' => 'ISP'],
    '62.55.' => ['name' => 'Bouygues Telecom', 'asn' => 'AS5410', 'country' => 'FR', 'type' => 'ISP'],
    '62.56.' => ['name' => 'Bouygues Telecom', 'asn' => 'AS5410', 'country' => 'FR', 'type' => 'ISP'],
    '62.57.' => ['name' => 'Bouygues Telecom', 'asn' => 'AS5410', 'country' => 'FR', 'type' => 'ISP'],
    '62.58.' => ['name' => 'Bouygues Telecom', 'asn' => 'AS5410', 'country' => 'FR', 'type' => 'ISP'],
    '62.59.' => ['name' => 'Bouygues Telecom', 'asn' => 'AS5410', 'country' => 'FR', 'type' => 'ISP'],
    '62.60.' => ['name' => 'Bouygues Telecom', 'asn' => 'AS5410', 'country' => 'FR', 'type' => 'ISP'],
    '62.61.' => ['name' => 'Bouygues Telecom', 'asn' => 'AS5410', 'country' => 'FR', 'type' => 'ISP'],
    '62.62.' => ['name' => 'Bouygues Telecom', 'asn' => 'AS5410', 'country' => 'FR', 'type' => 'ISP'],
    '62.63.' => ['name' => 'Bouygues Telecom', 'asn' => 'AS5410', 'country' => 'FR', 'type' => 'ISP'],
    '62.64.' => ['name' => 'Bouygues Telecom', 'asn' => 'AS5410', 'country' => 'FR', 'type' => 'ISP'],
    '62.65.' => ['name' => 'Bouygues Telecom', 'asn' => 'AS5410', 'country' => 'FR', 'type' => 'ISP'],
    '62.66.' => ['name' => 'Bouygues Telecom', 'asn' => 'AS5410', 'country' => 'FR', 'type' => 'ISP'],
    '62.67.' => ['name' => 'Bouygues Telecom', 'asn' => 'AS5410', 'country' => 'FR', 'type' => 'ISP'],
    '62.68.' => ['name' => 'Bouygues Telecom', 'asn' => 'AS5410', 'country' => 'FR', 'type' => 'ISP'],
    '62.69.' => ['name' => 'Bouygues Telecom', 'asn' => 'AS5410', 'country' => 'FR', 'type' => 'ISP'],
    '62.70.' => ['name' => 'Bouygues Telecom', 'asn' => 'AS5410', 'country' => 'FR', 'type' => 'ISP'],
    '62.71.' => ['name' => 'Bouygues Telecom', 'asn' => 'AS5410', 'country' => 'FR', 'type' => 'ISP'],
    '62.72.' => ['name' => 'Bouygues Telecom', 'asn' => 'AS5410', 'country' => 'FR', 'type' => 'ISP'],
    '62.73.' => ['name' => 'Bouygues Telecom', 'asn' => 'AS5410', 'country' => 'FR', 'type' => 'ISP'],
    '62.74.' => ['name' => 'Bouygues Telecom', 'asn' => 'AS5410', 'country' => 'FR', 'type' => 'ISP'],
    '62.75.' => ['name' => 'Bouygues Telecom', 'asn' => 'AS5410', 'country' => 'FR', 'type' => 'ISP'],
    '62.76.' => ['name' => 'Bouygues Telecom', 'asn' => 'AS5410', 'country' => 'FR', 'type' => 'ISP'],
    '62.77.' => ['name' => 'Bouygues Telecom', 'asn' => 'AS5410', 'country' => 'FR', 'type' => 'ISP'],
    '62.78.' => ['name' => 'Bouygues Telecom', 'asn' => 'AS5410', 'country' => 'FR', 'type' => 'ISP'],
    '62.79.' => ['name' => 'Bouygues Telecom', 'asn' => 'AS5410', 'country' => 'FR', 'type' => 'ISP'],
    '62.80.' => ['name' => 'Bouygues Telecom', 'asn' => 'AS5410', 'country' => 'FR', 'type' => 'ISP'],
    '62.81.' => ['name' => 'Bouygues Telecom', 'asn' => 'AS5410', 'country' => 'FR', 'type' => 'ISP'],
    '62.82.' => ['name' => 'Bouygues Telecom', 'asn' => 'AS5410', 'country' => 'FR', 'type' => 'ISP'],
    '62.83.' => ['name' => 'Bouygues Telecom', 'asn' => 'AS5410', 'country' => 'FR', 'type' => 'ISP'],
    '62.84.' => ['name' => 'Bouygues Telecom', 'asn' => 'AS5410', 'country' => 'FR', 'type' => 'ISP'],
    '62.85.' => ['name' => 'Bouygues Telecom', 'asn' => 'AS5410', 'country' => 'FR', 'type' => 'ISP'],
    '62.86.' => ['name' => 'Bouygues Telecom', 'asn' => 'AS5410', 'country' => 'FR', 'type' => 'ISP'],
    '62.87.' => ['name' => 'Bouygues Telecom', 'asn' => 'AS5410', 'country' => 'FR', 'type' => 'ISP'],
    '62.88.' => ['name' => 'Bouygues Telecom', 'asn' => 'AS5410', 'country' => 'FR', 'type' => 'ISP'],
    '62.89.' => ['name' => 'Bouygues Telecom', 'asn' => 'AS5410', 'country' => 'FR', 'type' => 'ISP'],
    '62.90.' => ['name' => 'Bouygues Telecom', 'asn' => 'AS5410', 'country' => 'FR', 'type' => 'ISP'],
    '62.91.' => ['name' => 'Bouygues Telecom', 'asn' => 'AS5410', 'country' => 'FR', 'type' => 'ISP'],
    '62.92.' => ['name' => 'Bouygues Telecom', 'asn' => 'AS5410', 'country' => 'FR', 'type' => 'ISP'],
    '62.93.' => ['name' => 'Bouygues Telecom', 'asn' => 'AS5410', 'country' => 'FR', 'type' => 'ISP'],
    '62.94.' => ['name' => 'Bouygues Telecom', 'asn' => 'AS5410', 'country' => 'FR', 'type' => 'ISP'],
    '62.95.' => ['name' => 'Bouygues Telecom', 'asn' => 'AS5410', 'country' => 'FR', 'type' => 'ISP'],
    '62.96.' => ['name' => 'Bouygues Telecom', 'asn' => 'AS5410', 'country' => 'FR', 'type' => 'ISP'],
    '62.97.' => ['name' => 'Bouygues Telecom', 'asn' => 'AS5410', 'country' => 'FR', 'type' => 'ISP'],
    '62.98.' => ['name' => 'Bouygues Telecom', 'asn' => 'AS5410', 'country' => 'FR', 'type' => 'ISP'],
    '62.99.' => ['name' => 'Bouygues Telecom', 'asn' => 'AS5410', 'country' => 'FR', 'type' => 'ISP'],
    '62.100.' => ['name' => 'Bouygues Telecom', 'asn' => 'AS5410', 'country' => 'FR', 'type' => 'ISP'],
    '62.101.' => ['name' => 'Bouygues Telecom', 'asn' => 'AS5410', 'country' => 'FR', 'type' => 'ISP'],
    '62.102.' => ['name' => 'Bouygues Telecom', 'asn' => 'AS5410', 'country' => 'FR', 'type' => 'ISP'],
    '62.103.' => ['name' => 'Bouygues Telecom', 'asn' => 'AS5410', 'country' => 'FR', 'type' => 'ISP'],
    '62.104.' => ['name' => 'Bouygues Telecom', 'asn' => 'AS5410', 'country' => 'FR', 'type' => 'ISP'],
    '62.105.' => ['name' => 'Bouygues Telecom', 'asn' => 'AS5410', 'country' => 'FR', 'type' => 'ISP'],
    '62.106.' => ['name' => 'Bouygues Telecom', 'asn' => 'AS5410', 'country' => 'FR', 'type' => 'ISP'],
    '62.107.' => ['name' => 'Bouygues Telecom', 'asn' => 'AS5410', 'country' => 'FR', 'type' => 'ISP'],
    '62.108.' => ['name' => 'Bouygues Telecom', 'asn' => 'AS5410', 'country' => 'FR', 'type' => 'ISP'],
    '62.109.' => ['name' => 'Bouygues Telecom', 'asn' => 'AS5410', 'country' => 'FR', 'type' => 'ISP'],
    '62.110.' => ['name' => 'Bouygues Telecom', 'asn' => 'AS5410', 'country' => 'FR', 'type' => 'ISP'],
    '62.111.' => ['name' => 'Bouygues Telecom', 'asn' => 'AS5410', 'country' => 'FR', 'type' => 'ISP'],
    '62.112.' => ['name' => 'Bouygues Telecom', 'asn' => 'AS5410', 'country' => 'FR', 'type' => 'ISP'],
    '62.113.' => ['name' => 'Bouygues Telecom', 'asn' => 'AS5410', 'country' => 'FR', 'type' => 'ISP'],
    '62.114.' => ['name' => 'Bouygues Telecom', 'asn' => 'AS5410', 'country' => 'FR', 'type' => 'ISP'],
    '62.115.' => ['name' => 'Bouygues Telecom', 'asn' => 'AS5410', 'country' => 'FR', 'type' => 'ISP'],
    '62.116.' => ['name' => 'Bouygues Telecom', 'asn' => 'AS5410', 'country' => 'FR', 'type' => 'ISP'],
    '62.117.' => ['name' => 'Bouygues Telecom', 'asn' => 'AS5410', 'country' => 'FR', 'type' => 'ISP'],
    '62.118.' => ['name' => 'Bouygues Telecom', 'asn' => 'AS5410', 'country' => 'FR', 'type' => 'ISP'],
    '62.119.' => ['name' => 'Bouygues Telecom', 'asn' => 'AS5410', 'country' => 'FR', 'type' => 'ISP'],
    '62.120.' => ['name' => 'Bouygues Telecom', 'asn' => 'AS5410', 'country' => 'FR', 'type' => 'ISP'],
    '62.121.' => ['name' => 'Bouygues Telecom', 'asn' => 'AS5410', 'country' => 'FR', 'type' => 'ISP'],
    '62.122.' => ['name' => 'Bouygues Telecom', 'asn' => 'AS5410', 'country' => 'FR', 'type' => 'ISP'],
    '62.123.' => ['name' => 'Bouygues Telecom', 'asn' => 'AS5410', 'country' => 'FR', 'type' => 'ISP'],
    '62.124.' => ['name' => 'Bouygues Telecom', 'asn' => 'AS5410', 'country' => 'FR', 'type' => 'ISP'],
    '62.125.' => ['name' => 'Bouygues Telecom', 'asn' => 'AS5410', 'country' => 'FR', 'type' => 'ISP'],
    '62.126.' => ['name' => 'Bouygues Telecom', 'asn' => 'AS5410', 'country' => 'FR', 'type' => 'ISP'],
    '62.127.' => ['name' => 'Bouygues Telecom', 'asn' => 'AS5410', 'country' => 'FR', 'type' => 'ISP'],
    '2a01:cb10:' => ['name' => 'Bouygues Telecom', 'asn' => 'AS5410', 'country' => 'FR', 'type' => 'ISP', 'ipv6' => true],
    
    // Numericable-SFR (Cable)
    '82.64.' => ['name' => 'Numericable-SFR', 'asn' => 'AS21502', 'country' => 'FR', 'type' => 'Cable'],
    '82.65.' => ['name' => 'Numericable-SFR', 'asn' => 'AS21502', 'country' => 'FR', 'type' => 'Cable'],
    
    // OVH (Hosting - FR)
    '5.135.' => ['name' => 'OVH SAS', 'asn' => 'AS16276', 'country' => 'FR', 'type' => 'Hosting'],
    '5.196.' => ['name' => 'OVH SAS', 'asn' => 'AS16276', 'country' => 'FR', 'type' => 'Hosting'],
    '37.59.' => ['name' => 'OVH SAS', 'asn' => 'AS16276', 'country' => 'FR', 'type' => 'Hosting'],
    '46.105.' => ['name' => 'OVH SAS', 'asn' => 'AS16276', 'country' => 'FR', 'type' => 'Hosting'],
    '51.255.' => ['name' => 'OVH SAS', 'asn' => 'AS16276', 'country' => 'FR', 'type' => 'Hosting'],
    '54.36.' => ['name' => 'OVH SAS', 'asn' => 'AS16276', 'country' => 'FR', 'type' => 'Hosting'],
    '91.121.' => ['name' => 'OVH SAS', 'asn' => 'AS16276', 'country' => 'FR', 'type' => 'Hosting'],
    '188.165.' => ['name' => 'OVH SAS', 'asn' => 'AS16276', 'country' => 'FR', 'type' => 'Hosting'],
    '213.186.' => ['name' => 'OVH SAS', 'asn' => 'AS16276', 'country' => 'FR', 'type' => 'Hosting'],
    '217.182.' => ['name' => 'OVH SAS', 'asn' => 'AS16276', 'country' => 'FR', 'type' => 'Hosting'],
    
    /***** ÖSTERREICH *****/
    // A1 Telekom Austria
    '84.112.' => ['name' => 'A1 Telekom Austria', 'asn' => 'AS8447', 'country' => 'AT', 'type' => 'ISP'],
    '84.113.' => ['name' => 'A1 Telekom Austria', 'asn' => 'AS8447', 'country' => 'AT', 'type' => 'ISP'],
    '84.114.' => ['name' => 'A1 Telekom Austria', 'asn' => 'AS8447', 'country' => 'AT', 'type' => 'ISP'],
    '84.115.' => ['name' => 'A1 Telekom Austria', 'asn' => 'AS8447', 'country' => 'AT', 'type' => 'ISP'],
    '84.116.' => ['name' => 'A1 Telekom Austria', 'asn' => 'AS8447', 'country' => 'AT', 'type' => 'ISP'],
    '84.117.' => ['name' => 'A1 Telekom Austria', 'asn' => 'AS8447', 'country' => 'AT', 'type' => 'ISP'],
    '84.118.' => ['name' => 'A1 Telekom Austria', 'asn' => 'AS8447', 'country' => 'AT', 'type' => 'ISP'],
    '84.119.' => ['name' => 'A1 Telekom Austria', 'asn' => 'AS8447', 'country' => 'AT', 'type' => 'ISP'],
    '85.126.' => ['name' => 'A1 Telekom Austria', 'asn' => 'AS8447', 'country' => 'AT', 'type' => 'ISP'],
    '85.127.' => ['name' => 'A1 Telekom Austria', 'asn' => 'AS8447', 'country' => 'AT', 'type' => 'ISP'],
    
    // Magenta (T-Mobile Austria)
    '77.116.' => ['name' => 'Magenta Telekom', 'asn' => 'AS8447', 'country' => 'AT', 'type' => 'ISP'],
    '77.117.' => ['name' => 'Magenta Telekom', 'asn' => 'AS8447', 'country' => 'AT', 'type' => 'ISP'],
    '80.108.' => ['name' => 'Magenta Telekom', 'asn' => 'AS8447', 'country' => 'AT', 'type' => 'ISP'],
    '80.109.' => ['name' => 'Magenta Telekom', 'asn' => 'AS8447', 'country' => 'AT', 'type' => 'ISP'],
    '80.110.' => ['name' => 'Magenta Telekom', 'asn' => 'AS8447', 'country' => 'AT', 'type' => 'ISP'],
    '80.111.' => ['name' => 'Magenta Telekom', 'asn' => 'AS8447', 'country' => 'AT', 'type' => 'ISP'],
    
    // Drei Austria
    '77.182.' => ['name' => 'Drei Austria', 'asn' => 'AS25255', 'country' => 'AT', 'type' => 'ISP'],
    '77.183.' => ['name' => 'Drei Austria', 'asn' => 'AS25255', 'country' => 'AT', 'type' => 'ISP'],
    '83.64.' => ['name' => 'Drei Austria', 'asn' => 'AS25255', 'country' => 'AT', 'type' => 'ISP'],
    '83.65.' => ['name' => 'Drei Austria', 'asn' => 'AS25255', 'country' => 'AT', 'type' => 'ISP'],
    
    /***** SCHWEIZ *****/
    // Swisscom
    '84.226.' => ['name' => 'Swisscom AG', 'asn' => 'AS3303', 'country' => 'CH', 'type' => 'ISP'],
    '84.227.' => ['name' => 'Swisscom AG', 'asn' => 'AS3303', 'country' => 'CH', 'type' => 'ISP'],
    '84.228.' => ['name' => 'Swisscom AG', 'asn' => 'AS3303', 'country' => 'CH', 'type' => 'ISP'],
    '84.229.' => ['name' => 'Swisscom AG', 'asn' => 'AS3303', 'country' => 'CH', 'type' => 'ISP'],
    '85.0.' => ['name' => 'Swisscom AG', 'asn' => 'AS3303', 'country' => 'CH', 'type' => 'ISP'],
    '85.1.' => ['name' => 'Swisscom AG', 'asn' => 'AS3303', 'country' => 'CH', 'type' => 'ISP'],
    '85.2.' => ['name' => 'Swisscom AG', 'asn' => 'AS3303', 'country' => 'CH', 'type' => 'ISP'],
    '85.3.' => ['name' => 'Swisscom AG', 'asn' => 'AS3303', 'country' => 'CH', 'type' => 'ISP'],
    
    // Sunrise
    '85.195.' => ['name' => 'Sunrise GmbH', 'asn' => 'AS6774', 'country' => 'CH', 'type' => 'ISP'],
    '85.196.' => ['name' => 'Sunrise GmbH', 'asn' => 'AS6774', 'country' => 'CH', 'type' => 'ISP'],
    
    // Salt
    '85.8.' => ['name' => 'Salt Mobile', 'asn' => 'AS6739', 'country' => 'CH', 'type' => 'ISP'],
    '85.9.' => ['name' => 'Salt Mobile', 'asn' => 'AS6739', 'country' => 'CH', 'type' => 'ISP'],
    
    /***** ITALIEN *****/
    // TIM
    '79.0.' => ['name' => 'TIM (Telecom Italia)', 'asn' => 'AS3269', 'country' => 'IT', 'type' => 'ISP'],
    '79.1.' => ['name' => 'TIM (Telecom Italia)', 'asn' => 'AS3269', 'country' => 'IT', 'type' => 'ISP'],
    '79.2.' => ['name' => 'TIM (Telecom Italia)', 'asn' => 'AS3269', 'country' => 'IT', 'type' => 'ISP'],
    '79.3.' => ['name' => 'TIM (Telecom Italia)', 'asn' => 'AS3269', 'country' => 'IT', 'type' => 'ISP'],
    '79.4.' => ['name' => 'TIM (Telecom Italia)', 'asn' => 'AS3269', 'country' => 'IT', 'type' => 'ISP'],
    '79.5.' => ['name' => 'TIM (Telecom Italia)', 'asn' => 'AS3269', 'country' => 'IT', 'type' => 'ISP'],
    '79.6.' => ['name' => 'TIM (Telecom Italia)', 'asn' => 'AS3269', 'country' => 'IT', 'type' => 'ISP'],
    '79.7.' => ['name' => 'TIM (Telecom Italia)', 'asn' => 'AS3269', 'country' => 'IT', 'type' => 'ISP'],
    
    // Vodafone IT
    '87.0.' => ['name' => 'Vodafone Italia', 'asn' => 'AS30722', 'country' => 'IT', 'type' => 'ISP'],
    '87.1.' => ['name' => 'Vodafone Italia', 'asn' => 'AS30722', 'country' => 'IT', 'type' => 'ISP'],
    '87.2.' => ['name' => 'Vodafone Italia', 'asn' => 'AS30722', 'country' => 'IT', 'type' => 'ISP'],
    '87.3.' => ['name' => 'Vodafone Italia', 'asn' => 'AS30722', 'country' => 'IT', 'type' => 'ISP'],
    
    /***** SPANIEN *****/
    // Movistar
    '80.0.' => ['name' => 'Movistar (Telefónica)', 'asn' => 'AS3352', 'country' => 'ES', 'type' => 'ISP'],
    '80.1.' => ['name' => 'Movistar (Telefónica)', 'asn' => 'AS3352', 'country' => 'ES', 'type' => 'ISP'],
    '80.2.' => ['name' => 'Movistar (Telefónica)', 'asn' => 'AS3352', 'country' => 'ES', 'type' => 'ISP'],
    
    // Vodafone ES
    '88.0.' => ['name' => 'Vodafone España', 'asn' => 'AS12430', 'country' => 'ES', 'type' => 'ISP'],
    '88.1.' => ['name' => 'Vodafone España', 'asn' => 'AS12430', 'country' => 'ES', 'type' => 'ISP'],
    
    /***** NIEDERLANDE *****/
    // KPN
    '84.24.' => ['name' => 'KPN B.V.', 'asn' => 'AS1136', 'country' => 'NL', 'type' => 'ISP'],
    '84.25.' => ['name' => 'KPN B.V.', 'asn' => 'AS1136', 'country' => 'NL', 'type' => 'ISP'],
    '84.26.' => ['name' => 'KPN B.V.', 'asn' => 'AS1136', 'country' => 'NL', 'type' => 'ISP'],
    '84.27.' => ['name' => 'KPN B.V.', 'asn' => 'AS1136', 'country' => 'NL', 'type' => 'ISP'],
    '85.148.' => ['name' => 'KPN B.V.', 'asn' => 'AS1136', 'country' => 'NL', 'type' => 'ISP'],
    '85.149.' => ['name' => 'KPN B.V.', 'asn' => 'AS1136', 'country' => 'NL', 'type' => 'ISP'],
    
    /***** GROSSBRITANNIEN *****/
    // BT
    '81.0.' => ['name' => 'British Telecom', 'asn' => 'AS2856', 'country' => 'GB', 'type' => 'ISP'],
    '81.1.' => ['name' => 'British Telecom', 'asn' => 'AS2856', 'country' => 'GB', 'type' => 'ISP'],
    '81.2.' => ['name' => 'British Telecom', 'asn' => 'AS2856', 'country' => 'GB', 'type' => 'ISP'],
    '86.0.' => ['name' => 'British Telecom', 'asn' => 'AS2856', 'country' => 'GB', 'type' => 'ISP'],
    '86.1.' => ['name' => 'British Telecom', 'asn' => 'AS2856', 'country' => 'GB', 'type' => 'ISP'],
    
    // Virgin Media
    '81.96.' => ['name' => 'Virgin Media', 'asn' => 'AS5089', 'country' => 'GB', 'type' => 'ISP'],
    '81.97.' => ['name' => 'Virgin Media', 'asn' => 'AS5089', 'country' => 'GB', 'type' => 'ISP'],
    
    /***** USA / GLOBALE PROVIDER *****/
    // Google
    '8.8.' => ['name' => 'Google LLC', 'asn' => 'AS15169', 'country' => 'US', 'type' => 'Cloud/CDN'],
    '142.250.' => ['name' => 'Google LLC', 'asn' => 'AS15169', 'country' => 'US', 'type' => 'Cloud/CDN'],
    '172.217.' => ['name' => 'Google LLC', 'asn' => 'AS15169', 'country' => 'US', 'type' => 'Cloud/CDN'],
    '216.58.' => ['name' => 'Google LLC', 'asn' => 'AS15169', 'country' => 'US', 'type' => 'Cloud/CDN'],
    
    // Cloudflare
    '1.1.1.' => ['name' => 'Cloudflare, Inc.', 'asn' => 'AS13335', 'country' => 'US', 'type' => 'CDN'],
    '104.16.' => ['name' => 'Cloudflare, Inc.', 'asn' => 'AS13335', 'country' => 'US', 'type' => 'CDN'],
    '172.64.' => ['name' => 'Cloudflare, Inc.', 'asn' => 'AS13335', 'country' => 'US', 'type' => 'CDN'],
    
    // Amazon AWS
    '52.' => ['name' => 'Amazon.com, Inc.', 'asn' => 'AS16509', 'country' => 'US', 'type' => 'Cloud'],
    '54.' => ['name' => 'Amazon.com, Inc.', 'asn' => 'AS16509', 'country' => 'US', 'type' => 'Cloud'],
    '35.' => ['name' => 'Amazon.com, Inc.', 'asn' => 'AS16509', 'country' => 'US', 'type' => 'Cloud'],
    
    // Microsoft Azure
    '13.' => ['name' => 'Microsoft Corporation', 'asn' => 'AS8075', 'country' => 'US', 'type' => 'Cloud'],
    '40.' => ['name' => 'Microsoft Corporation', 'asn' => 'AS8075', 'country' => 'US', 'type' => 'Cloud'],
    '20.' => ['name' => 'Microsoft Corporation', 'asn' => 'AS8075', 'country' => 'US', 'type' => 'Cloud'],
    
    // DigitalOcean
    '138.197.' => ['name' => 'DigitalOcean, LLC', 'asn' => 'AS14061', 'country' => 'US', 'type' => 'Cloud Hosting'],
    '159.203.' => ['name' => 'DigitalOcean, LLC', 'asn' => 'AS14061', 'country' => 'US', 'type' => 'Cloud Hosting'],
    '167.99.' => ['name' => 'DigitalOcean, LLC', 'asn' => 'AS14061', 'country' => 'US', 'type' => 'Cloud Hosting'],
    
    /***** PRIVATE NETZWERKE *****/
    '192.168.' => ['name' => 'Privates Netzwerk', 'asn' => null, 'country' => null, 'type' => 'Private'],
    '10.' => ['name' => 'Privates Netzwerk', 'asn' => null, 'country' => null, 'type' => 'Private'],
    '172.16.' => ['name' => 'Privates Netzwerk', 'asn' => null, 'country' => null, 'type' => 'Private'],
    '172.17.' => ['name' => 'Privates Netzwerk', 'asn' => null, 'country' => null, 'type' => 'Private'],
    '172.18.' => ['name' => 'Privates Netzwerk', 'asn' => null, 'country' => null, 'type' => 'Private'],
    '172.19.' => ['name' => 'Privates Netzwerk', 'asn' => null, 'country' => null, 'type' => 'Private'],
    '172.20.' => ['name' => 'Privates Netzwerk', 'asn' => null, 'country' => null, 'type' => 'Private'],
    '172.21.' => ['name' => 'Privates Netzwerk', 'asn' => null, 'country' => null, 'type' => 'Private'],
    '172.22.' => ['name' => 'Privates Netzwerk', 'asn' => null, 'country' => null, 'type' => 'Private'],
    '172.23.' => ['name' => 'Privates Netzwerk', 'asn' => null, 'country' => null, 'type' => 'Private'],
    '172.24.' => ['name' => 'Privates Netzwerk', 'asn' => null, 'country' => null, 'type' => 'Private'],
    '172.25.' => ['name' => 'Privates Netzwerk', 'asn' => null, 'country' => null, 'type' => 'Private'],
    '172.26.' => ['name' => 'Privates Netzwerk', 'asn' => null, 'country' => null, 'type' => 'Private'],
    '172.27.' => ['name' => 'Privates Netzwerk', 'asn' => null, 'country' => null, 'type' => 'Private'],
    '172.28.' => ['name' => 'Privates Netzwerk', 'asn' => null, 'country' => null, 'type' => 'Private'],
    '172.29.' => ['name' => 'Privates Netzwerk', 'asn' => null, 'country' => null, 'type' => 'Private'],
    '172.30.' => ['name' => 'Privates Netzwerk', 'asn' => null, 'country' => null, 'type' => 'Private'],
    '172.31.' => ['name' => 'Privates Netzwerk', 'asn' => null, 'country' => null, 'type' => 'Private'],
];
