services:
  backend:
    build: ./backend
    container_name: email-agent-backend
    ports:
      - "4000:4000"
    env_file:
      - ./backend/.env
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: email-agent-frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
    restart: unless-stopped
